# Generated by Django 5.1.1 on 2024-10-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
